#+TITLE: Test Report

Report generated on 05-Apr-2018 at 14:58:35
by[[https://pypi.python.org/pypi/pytest-html][pytest-html]] v1.16.1

** Environment

| Packages   | {'py': '1.5.3', 'pluggy': '0.6.0', 'pytest': '3.5.0'}        |
| Platform   | Linux-4.10.0-38-generic-x86\_64-with-LinuxMint-18.3-sylvia   |
| Plugins    | {'metadata': '1.6.0', 'html': '1.16.1'}                      |
| Python     | 3.5.2                                                        |

** Summary

13 tests ran in 25.71 seconds.

(Un)check the boxes to filter the results.

7 passed, 0 skipped, 6 failed, 0 errors, 0 expected failures, 0
unexpected passes

** Results

Result

Test

Duration

Links

No results found. Try to check the filters

Failed

Testing/test\_Data\_transforms.py::test\_standardise\_data

0.00

#+BEGIN_HTML
  <div class="log">
#+END_HTML

data\_extra\_info = <ct\_analysing\_library.ct\_data.CTData object at
0x7fdb61853be0>\\
\\
def test\_standardise\_data(data\_extra\_info):\\
> standarise\_data()\\
E TypeError: standarise\_data() missing 3 required positional arguments:
'df', 'features', and 'groupby'\\
\\
Testing/test\_Data\_transforms.py:7: TypeError\\

#+BEGIN_HTML
  </div>
#+END_HTML

Failed

Testing/test\_Data\_transforms.py::test\_perform\_pca

0.00

#+BEGIN_HTML
  <div class="log">
#+END_HTML

data\_extra\_info = <ct\_analysing\_library.ct\_data.CTData object at
0x7fdb6182b4a8>\\
\\
def test\_perform\_pca(data\_extra\_info):\\
> perform\_pca()\\
E TypeError: perform\_pca() missing 3 required positional arguments:
'df', 'features', and 'groupby'\\
\\
Testing/test\_Data\_transforms.py:11: TypeError\\

#+BEGIN_HTML
  </div>
#+END_HTML

Failed

Testing/test\_Data\_transforms.py::test\_box\_cox\_data

0.00

#+BEGIN_HTML
  <div class="log">
#+END_HTML

data\_extra\_info = <ct\_analysing\_library.ct\_data.CTData object at
0x7fdb61712358>\\
\\
def test\_box\_cox\_data(data\_extra\_info):\\
> box\_cox\_data()\\
E TypeError: box\_cox\_data() missing 1 required positional argument:
'values\_array'\\
\\
Testing/test\_Data\_transforms.py:15: TypeError\\

#+BEGIN_HTML
  </div>
#+END_HTML

Failed

Testing/test\_Data\_transforms.py::test\_pca\_to\_table

0.00

#+BEGIN_HTML
  <div class="log">
#+END_HTML

data\_extra\_info = <ct\_analysing\_library.ct\_data.CTData object at
0x7fdb616a4f60>\\
\\
def test\_pca\_to\_table(data\_extra\_info):\\
> pca\_to\_table()\\
E TypeError: pca\_to\_table() missing 2 required positional arguments:
'pca' and 'pca\_df'\\
\\
Testing/test\_Data\_transforms.py:19: TypeError\\

#+BEGIN_HTML
  </div>
#+END_HTML

Failed

Testing/test\_Statistical\_tests.py::test\_baysian\_hypothesis\_test

0.00

#+BEGIN_HTML
  <div class="log">
#+END_HTML

data\_extra\_info = <ct\_analysing\_library.ct\_data.CTData object at
0x7fdb6189ae48>\\
\\
def test\_baysian\_hypothesis\_test(data\_extra\_info):\\
> baysian\_hypothesis\_test()\\
E TypeError: baysian\_hypothesis\_test() missing 4 required positional
arguments: 'group1', 'group2', 'group1\_name', and 'group2\_name'\\
\\
Testing/test\_Statistical\_tests.py:7: TypeError\\

#+BEGIN_HTML
  </div>
#+END_HTML

Failed

Testing/test\_Statistical\_tests.py::test\_test\_normality

0.00

#+BEGIN_HTML
  <div class="log">
#+END_HTML

data\_extra\_info = <ct\_analysing\_library.ct\_data.CTData object at
0x7fdb616a45c0>\\
\\
def test\_test\_normality(data\_extra\_info):\\
> test\_normality()\\
E NameError: name 'test\_normality' is not defined\\
\\
Testing/test\_Statistical\_tests.py:11: NameError\\

#+BEGIN_HTML
  </div>
#+END_HTML

Passed

Testing/test\_CTData.py::test\_load\_data

0.31

#+BEGIN_HTML
  <div class="empty log">
#+END_HTML

No log output captured.

#+BEGIN_HTML
  </div>
#+END_HTML

Passed

Testing/test\_CTData.py::test\_NoDataFoundException

0.00

#+BEGIN_HTML
  <div class="empty log">
#+END_HTML

No log output captured.

#+BEGIN_HTML
  </div>
#+END_HTML

Passed

Testing/test\_CTData.py::test\_clean\_data\_maximum\_removed

0.01

#+BEGIN_HTML
  <div class="empty log">
#+END_HTML

No log output captured.

#+BEGIN_HTML
  </div>
#+END_HTML

Passed

Testing/test\_CTData.py::test\_clean\_data\_minimum\_removed

0.00

#+BEGIN_HTML
  <div class="empty log">
#+END_HTML

No log output captured.

#+BEGIN_HTML
  </div>
#+END_HTML

Passed

Testing/test\_CTData.py::test\_load\_additional\_data

1.78

#+BEGIN_HTML
  <div class="empty log">
#+END_HTML

No log output captured.

#+BEGIN_HTML
  </div>
#+END_HTML

Passed

Testing/test\_CTData.py::test\_load\_additional\_data\_no\_data

0.00

#+BEGIN_HTML
  <div class="empty log">
#+END_HTML

No log output captured.

#+BEGIN_HTML
  </div>
#+END_HTML

Passed

Testing/test\_CTData.py::test\_aggregate\_spike\_averages

0.04

#+BEGIN_HTML
  <div class="empty log">
#+END_HTML

No log output captured.

#+BEGIN_HTML
  </div>
#+END_HTML
